# Copyright Amazon.com, Inc. or its affiliates. All Rights Reserved.
# SPDX-License-Identifier: MIT-0
#
# Permission is hereby granted, free of charge, to any person obtaining a copy of this
# software and associated documentation files (the "Software"), to deal in the Software
# without restriction, including without limitation the rights to use, copy, modify,
# merge, publish, distribute, sublicense, and/or sell copies of the Software, and to
# permit persons to whom the Software is furnished to do so.
# 
# THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR IMPLIED,
# INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY, FITNESS FOR A
# PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE AUTHORS OR COPYRIGHT
# HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER LIABILITY, WHETHER IN AN ACTION
# OF CONTRACT, TORT OR OTHERWISE, ARISING FROM, OUT OF OR IN CONNECTION WITH THE
# SOFTWARE OR THE USE OR OTHER DEALINGS IN THE SOFTWARE.

AWSTemplateFormatVersion: '2010-09-09'
Description: 'Template for CloudFront'

Resources:
  rCFDistributionDeploymentPolicy:
    Type: AWS::CloudFront::ContinuousDeploymentPolicy
    Properties: 
      ContinuousDeploymentPolicyConfig: 
          Enabled: true
          StagingDistributionDnsNames: 
            - !GetAtt rCFDistribution.DomainName
          TrafficConfig: 
            SingleWeightConfig: 
              Weight: 0.10
            Type: SingleWeight

  rCFDistribution:
    Type: AWS::CloudFront::Distribution
    Properties:
      DistributionConfig:
        Staging: true
        Enabled: true
        Logging:
             Bucket: "cloudfront-continuous-deployment-bucket-accesslogging.s3.amazonaws.com"
             IncludeCookies: false
             Prefix: "cf-distribution-logs"
        HttpVersion: http2
        Origins:
        - DomainName: "cloudfront-continuous-deployment-bucket-2.s3.us-east-1.amazonaws.com"
          Id: CloudFront-Staging-Distribution
          S3OriginConfig: 
            OriginAccessIdentity: ''
          OriginAccessControlId: 'E2WCWCC6CA2Q9D'
        Comment: "Staging CloudFront Distribution"
        DefaultRootObject: "index.html"
        DefaultCacheBehavior:
          AllowedMethods:
          - GET
          - HEAD
          CachePolicyId: 658327ea-f89d-4fab-a63d-7e88639e58f6
          TargetOriginId: CloudFront-Staging-Distribution
          ViewerProtocolPolicy: https-only
        ViewerCertificate:
          CloudFrontDefaultCertificate: true
          MinimumProtocolVersion: TLSv1.2_2021

Outputs:  
  oStagingCFDistribution:
    Description: Domain Name of the CloudFront Distribution
    Value: !GetAtt rCFDistribution.Id
    Export:
      Name: StagingCloudFrontDistribution

  oCFDistributionDeploymentPolicyID:
    Description: Domain Name of the Continuous Deployment ID
    Value: !GetAtt rCFDistributionDeploymentPolicy.Id
    Export:
      Name: CFDistributionDeploymentPolicyID